version: '3'

services:

  redis_pubsub:
    build:
      context: .
      dockerfile: Dockerfile
    image: allocation-image
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=abc123
      - REDIS_HOST=redis
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./src:/src
      - ./tests:/tests
    entrypoint: 
      - python
      - /src/allocation/entrypoints/redis_eventconsumer.py

  api:
    image: allocation-image
    depends_on:
      - redis_pubsub
    environment:
      - DB_HOST=localhost
      - DB_PASSWORD=abc123
      - API_HOST=localhost
      - PYTHONDONTWRITEBYTECODE=1
      - REDIS_HOST=redis
    volumes:
      - ./src:/src
      - ./tests:/tests
    ports:
      - "8000:8000"

  postgres:
    image: postgres:12.18
    environment:
      - POSTGRES_USER=allocation
      - POSTGRES_PASSWORD=allocation
    ports:
      - "5433:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"