version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_HOST=localhost
      - DB_PASSWORD=abc123
      - API_HOST=localhost
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./src:/src
      - ./tests:/tests
    ports:
      - "8000:8000"

    
  postgres:
    image: postgres:12.18
    environment:
      - POSTGRES_USER=allocation
      - POSTGRES_PASSWORD=allocation
    ports:
      - "5433:5432"
